//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.13 at 01:27:59 AM EEST 
//


package com.prj.tuning.maplocator.plugin.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for map complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="map">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="afterRowAxis" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *           &lt;element name="afterColAxis" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;/choice>
 *         &lt;element name="address" type="{http://prj-tuning.com/mapdef}address" minOccurs="0"/>
 *         &lt;element name="conversion" type="{http://prj-tuning.com/mapdef}conversion" minOccurs="0"/>
 *         &lt;element name="length" type="{http://prj-tuning.com/mapdef}length" minOccurs="0"/>
 *         &lt;element name="rowAxis" type="{http://prj-tuning.com/mapdef}axisref" minOccurs="0"/>
 *         &lt;element name="colAxis" type="{http://prj-tuning.com/mapdef}axisref" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "map", propOrder = {
    "id",
    "pattern",
    "afterRowAxis",
    "afterColAxis",
    "address",
    "conversion",
    "length",
    "rowAxis",
    "colAxis"
})
public class Map {

    @XmlElement(required = true)
    protected String id;
    protected String pattern;
    protected Boolean afterRowAxis;
    protected Boolean afterColAxis;
    protected Address address;
    protected Conversion conversion;
    protected Length length;
    protected Axisref rowAxis;
    protected Axisref colAxis;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the pattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPattern(String value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the afterRowAxis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAfterRowAxis() {
        return afterRowAxis;
    }

    /**
     * Sets the value of the afterRowAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAfterRowAxis(Boolean value) {
        this.afterRowAxis = value;
    }

    /**
     * Gets the value of the afterColAxis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAfterColAxis() {
        return afterColAxis;
    }

    /**
     * Sets the value of the afterColAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAfterColAxis(Boolean value) {
        this.afterColAxis = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the conversion property.
     * 
     * @return
     *     possible object is
     *     {@link Conversion }
     *     
     */
    public Conversion getConversion() {
        return conversion;
    }

    /**
     * Sets the value of the conversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conversion }
     *     
     */
    public void setConversion(Conversion value) {
        this.conversion = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link Length }
     *     
     */
    public Length getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link Length }
     *     
     */
    public void setLength(Length value) {
        this.length = value;
    }

    /**
     * Gets the value of the rowAxis property.
     * 
     * @return
     *     possible object is
     *     {@link Axisref }
     *     
     */
    public Axisref getRowAxis() {
        return rowAxis;
    }

    /**
     * Sets the value of the rowAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Axisref }
     *     
     */
    public void setRowAxis(Axisref value) {
        this.rowAxis = value;
    }

    /**
     * Gets the value of the colAxis property.
     * 
     * @return
     *     possible object is
     *     {@link Axisref }
     *     
     */
    public Axisref getColAxis() {
        return colAxis;
    }

    /**
     * Sets the value of the colAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Axisref }
     *     
     */
    public void setColAxis(Axisref value) {
        this.colAxis = value;
    }

}
