//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.13 at 01:27:59 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://prj-tuning.com/mapdef", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.prj.tuning.maplocator.plugin.jaxb;
